// js/supabase.js

// Replace these with your actual Supabase project credentials
const SUPABASE_URL = "https://flphrbxmigmruqrmbpby.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZscGhyYnhtaWdtcnVxcm1icGJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEyODY2NjIsImV4cCI6MjA5Njg2MjY2Mn0.HQlIqdJjNLEnfhuKYUVWUaimTy5s9kuwEoqWyD8-Qic";

// Initialize the Supabase Client
const supabase = createClient(https://flphrbxmigmruqrmbpby.supabase.co, eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZscGhyYnhtaWdtcnVxcm1icGJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEyODY2NjIsImV4cCI6MjA5Njg2MjY2Mn0.HQlIqdJjNLEnfhuKYUVWUaimTy5s9kuwEoqWyD8-Qic);
